### PR TITLE
Topic/dogstatsd support

### PR DESCRIPTION
**Pull request by raing3**
Thanks for updating to support PHP8/Symfony 6 recently. :)

This PR relates to: https://github.com/BedrockStreaming/Statsd/pull/30

Needs to be merged after the above is merged + released and assumes the above PR will be released as 1.4.0.

### CODE REVIEW

**Review by jdecool — APPROVED** [review]

**Comment by Oliboy50** [comment]
the CI wasn't configured to run on PR from forks

now that it's fixed, could you fix the PR build, please?

**Comment by raing3** [comment]
The CI process will fail until https://github.com/BedrockStreaming/Statsd/pull/30 is merged and released due to composer not being able to resolve m6web/statsd ^1.4 (this PR assumes the m6web/statsd changes will be released as 1.4).

I've run the CI steps against my forked repo in an alt branch which points to my forked m6web/statsd library:
 * https://github.com/raing3/StatsdBundle/compare/topic/dogstatsd_support...topic/dogstatsd_support_alt
 * https://github.com/raing3/StatsdBundle/actions/runs/1924658846

Will fix up any issues which do appear once the other PR has been completed but I think there should be none/minimal.

**Review by jdecool — APPROVED** [review]

**Comment by raing3** [comment]
Thanks, looks like CI is passing now. Let me know if anything else is needed from me to get this PR merged and released as well.

**Comment by Oliboy50** [comment]
released in [v4.2.0](https://packagist.org/packages/m6web/statsd-bundle#v4.2.0)

**Comment by raing3** [comment]
Thanks very much. :)

**Pull request merged**
