### PR TITLE
PHP 8 & Symfony 6 compatibility

### LINKED ISSUE #84: PHP 8.x
Is it considered do make this bundle compatible with PHP 8.x
We currently use this bundle in production and upgrading our applications to PHP 8.1.
So at the moment we supressed the dependency because the composer.json does not allow PHP 8.1.
Do you have any planning for it ?
Thank you.

### PR DESCRIPTION
**Pull request by jdecool**
Closes #84 #78

This PR add the PHP 8.x branch support and allow Symfony 6.x installation.

### CODE REVIEW

**Review by Oliboy50 — APPROVED** [review]
👏

**Comment by jdecool** [comment]
Thanks @Oliboy50 

I've just add one commit to fix #78

**Review by Oliboy50 — APPROVED** [review]
`enableMagicCall` sounds more explicit indeed, and it is available using symfony 4 👏

**Comment by jdecool** [comment]
Tagged as https://github.com/BedrockStreaming/StatsdBundle/tree/v4.1.0

**Pull request merged**
